#!/usr/bin/env python3
"""
Bundle the modular visualizer into one self-contained HTML file.

    python3 tools/visualizer/build.py

Writes tools/visualizer/visualizer.html — no imports, no server, openable
straight off the desktop with file://.

Why this exists: file:// IS a secure context (getDisplayMedia works fine), but
Chrome blocks ES module imports from file:// under CORS. Inlining everything
into one classic script sidesteps that, so the page can be double-clicked or
bookmarked with no localhost server running.

Each mode becomes an IIFE so the four modules can each define name/render/reset
without colliding. themes.js and audio.js stay top-level, so the mode IIFEs
close over rampColor/bgColor/applyGlow exactly as the imports did.
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
MODES = ["bars", "scope", "radial", "particles"]

IMPORT_RE = re.compile(r"^\s*import\s.*?;\s*$", re.MULTILINE)
EXPORT_RE = re.compile(r"^export\s+(const|let|var|function|class)\s", re.MULTILINE)


def strip(src: str) -> str:
    """Remove import lines and the `export` keyword, leaving plain declarations."""
    src = IMPORT_RE.sub("", src)
    return EXPORT_RE.sub(r"\1 ", src)


def main() -> None:
    parts = [
        "// Generated by build.py from the modular source in this directory.",
        "// Edit audio.js / themes.js / modes/*.js and re-run build.py; do not edit this file.",
        "(function () {",
        "'use strict';",
        strip((HERE / "themes.js").read_text()),
        strip((HERE / "audio.js").read_text()),
    ]

    # Each mode in its own scope, exposing the same shape the imports produced.
    for m in MODES:
        body = strip((HERE / "modes" / f"{m}.js").read_text())
        parts.append(
            f"const {m} = (function () {{\n{body}\n"
            "return { name: name, render: render, "
            "reset: typeof reset === 'function' ? reset : undefined };\n"
            "})();"
        )

    parts.append(strip((HERE / "main.js").read_text()))
    parts.append("})();")
    bundle = "\n\n".join(parts)

    html = (HERE / "index.html").read_text()
    tag = '<script type="module" src="./main.js"></script>'
    if tag not in html:
        raise SystemExit("index.html no longer contains the expected module script tag")
    html = html.replace(tag, f"<script>\n{bundle}\n</script>")

    out = HERE / "visualizer.html"
    out.write_text(html)
    kb = out.stat().st_size / 1024
    print(f"wrote {out.relative_to(Path.cwd())} ({kb:.0f} KB, self-contained)")


if __name__ == "__main__":
    main()
